//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exp2.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WSCategoriasSoap")]
    public interface WSCategoriasSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategorias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCategorias", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCategoriasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCategoriasSoapChannel : Exp2.ServiceReference1.WSCategoriasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCategoriasSoapClient : System.ServiceModel.ClientBase<Exp2.ServiceReference1.WSCategoriasSoap>, Exp2.ServiceReference1.WSCategoriasSoap {
        
        public WSCategoriasSoapClient() {
        }
        
        public WSCategoriasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCategoriasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCategoriasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCategoriasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetCategorias() {
            return base.Channel.GetCategorias();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCategoriasAsync() {
            return base.Channel.GetCategoriasAsync();
        }
    }
}
